#!/bin/bash

#define bashscripts folder address in the ~/.bashrc and then source this file there. e.g.
# bashscripts="/home/$USER/bash_scripts"
# source "$bashscripts/bashrc_aliases"
# export PATH="$PATH:$bashscripts"

# load private info
$bashscripts/bashrc.private

# to access this file without looking for it every time
alias aliases_edit="gedit $bashscripts/bashrc_aliases &"
alias aliases_list="cat $bashscripts/bashrc_aliases"

#apt aliases
alias ins="sudo apt install"
alias upd="sudo apt update"
alias upg="sudo apt upgrade -y"
alias remove="sudo apt remove"

#note aliases
alias note="sh $bashscripts/note.sh"
alias n="sh $bashscripts/quicknote.sh"
alias ln="sh $bashscripts/lastnote.sh"
alias drafts="sh $bashscripts/searchdrafts.sh"

#github
alias git_switch="sh $bashscripts/git_switch.sh"
alias git_who="cat /home/$USER/opt/git_config/active_git_account"
git_all ()
{
    message=$*
    if [[ $(echo $message) ]]; then
        message=$message
    else
        message="quick commit"
    fi
    git status && git add --all && git commit -m "$message" && git push
}
git_activate ()
{
    echo $1 > "/home/$USER/opt/git_config/active_git_account"
}
git_clone ()
{
    # get the active git account name
    #account=$(<"/home/$USER/opt/git_config/active_git_account")
    account=$1
    git_link=$2
    # get everything from the first colon
    sublink=$(echo $git_link |
        sed 's/^[^:]*[:]//')
    # get repo name
    repo=$(echo $sublink |
        sed 's/.*\///')
    repo=${repo%.*}
    git clone git@${account}:$sublink &&
    cd $repo &&
    git_switch $account
}


#github gist aliases
alias gist="sh $bashscripts/gist.sh"
alias gistp="sh $bashscripts/publicgist.sh"
alias g="sh $bashscripts/quickgist.sh"

# solving ibus access problem
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus

# libarary
audiobooks_folder="/home/$USER/Documents/audiobook/"
export audiobooks_folder
alias libby="$bashscripts/overdrive/overdrive.sh download"
alias libby_list="ls -t /home/$USER/Downloads | grep \.odm\$ > /tmp/libby_list && cat -n /tmp/libby_list"
libby_get ()
{
    book_name=$(sed -n $1p /tmp/libby_list)
    libby "/home/$USER/Downloads/$book_name"
}

#hibernation
alias hib='sudo systemctl hibernate'

#shortcuts
alias search="sh $bashscripts/duckduckgo.sh"
alias contacts="sh $bashscripts/contacts.sh"
alias mic="sh $bashscripts/record.sh"
alias organize="sh $bashscripts/organize_photos_monthly_this_folder.sh"
alias jnb="jupyter notebook"
alias cb="sh $bashscripts/copy_file_to_clipboard.sh"
